name: watched_it_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.0
  http: 0.13.3
  webview_flutter: 2.0.10
  flutter_secure_storage: 4.2.1
  flutter_custom_clippers: 2.0.0
  provider: 6.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

